blog/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(
        r'^login/$',
        auth_views.login,
        name='login',
        kwargs={
            'template_name': 'blog/login.html'
        }
    ),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^list/$', views.post_list_view, name='list'),
    url(r'^write/$', views.write_post_view, name='write_post'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail_view, name='post_detail'),
    url(r'^post/(?P<pk>[0-9]+)/delete/$', views.post_delete_view, name='post_delete'),
    url(r'^post/(?P<pk>[0-9]+)/update/$', views.post_update_view, name='post_update'),
    url(r'^post/(?P<pk>[0-9]+)/newcomment/$', views.new_comment_view, name='new_comment'),
    url(r'^comment/(?P<pk>[0-9]+)/remove/$', views.comment_remove_view, name='comment_remove'),
    url(r'^mypage/$', views.mypage_view, name='mypage'),
    url(r'^mypage/changeavatar/$', views.change_avatar_view, name='change_avatar'),
    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^signout/$', views.signout_view, name='signout')

]

dustmq/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.shortcuts import render
from django.conf.urls.static import static
from django.conf import settings


def index(request):
    return render(request, 'index.html')


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^$', index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.core.mail import send_mail
from django.utils.translation import ugettext_lazy as _
from django.conf import settings


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, blank=False)
    content = models.TextField(blank=False)
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return self.text


class MyUserManager(BaseUserManager):
    def _create_user(self, username, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email address must be set')
        email = self.normalize_email(email)
        username = self.model.normalize_username(username)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, email, password, **extra_fields)

    def create_superuser(self, username, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(username, email, password, **extra_fields)


class MyUser(AbstractBaseUser, PermissionsMixin):
    """
    An abstract base class implementing a fully featured User model with
    admin-compliant permissions.

    Username and password are required. Other fields are optional.
    """
    email = models.EmailField(_('email address'), unique=True)
    username = models.CharField(
        _('username'),
        max_length=150,
        help_text=_('real name'),
    )
    nickname = models.CharField(
        _('nickname'),
        max_length=150,
        default='',
        help_text=_('Alias name to be called by others'),
        unique=True
    )

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    avatar = models.ImageField(
        _('avatar'),
        null=True,
        blank=True,
        upload_to='images/avatar/',
        default='images/avatar/default.jpeg'
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = MyUserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'nickname'
    REQUIRED_FIELDS = ['username', 'email']

    def get_full_name(self):
        return self.nickname

    def get_short_name(self):
        return self.nickname

    def email_user(self, subject, message, from_email=None, **kwargs):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email], **kwargs)

blog/forms.py
from django import forms
from .models import MyUser


class UserForm(forms.ModelForm):
    class Meta:
        model = MyUser
        fields = ['nickname','username', 'email', 'password']
        widgets = {
            'nickname': forms.TextInput(attrs={'class': 'form-control',  'placeholder': '로그인을 할 id 입니다.'}),
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '15자 이내로 입력 가능합니다.'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'nickname': '닉네임',
            'username': '이름',
            'email': '이메일',
            'password': '패스워드'
        }

    # 글자수 제한
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['maxlength'] = 15

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from django.contrib.auth import views as auth_views, login
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from .forms import *


class LogoutView(auth_views.LogoutView):
    next_page = reverse_lazy('blog:login')
    template_name = None


@login_required
def post_list_view(request):
    post_list =  Post.objects.order_by('-created_date')
    return render(request, 'blog/postlist.html', {'post_list': post_list, })


def post_detail_view(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/postdetail.html', {'post': post, })


def write_post_view(request):
    if request.method == 'POST':
        post = Post()
        post.author = request.user
        post.content = request.POST.get('content')
        post.title = request.POST.get('title')
        post.save()
        return redirect('blog:list')
    return render(request, 'blog/writepost.html', )


def post_delete_view(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('blog:list')


def post_update_view(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        post.title = request.POST.get('title')
        post.content = request.POST.get('content')
        post.save()
        return redirect('blog:list')
    return render(request, 'blog/updatepost.html', {'post': post, })


def new_comment_view(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comment = Comment()
    comment.post = post
    comment.author = request.user
    comment.text = request.POST.get('text')
    print(comment.text)
    comment.save()
    return redirect('blog:post_detail', pk=post.pk)


def comment_remove_view(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('blog:post_detail', pk=comment.post.pk)


def mypage_view(request):
    return render(request, 'blog/mypage.html', )


def change_avatar_view(request):
    avatar = request.FILES['avatar']
    print(avatar)
    request.user.avatar = avatar
    request.user.save()
    return render(request, 'blog/mypage.html', )


def signup_view(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            new_user = MyUser.objects.create_user(**form.cleaned_data)
            login(request, new_user)
            return redirect('blog:list')
    else:
        form = UserForm()
    return render(request, 'blog/signup.html', {'form':form})


def signout_view(request):
    user = request.user
    user.delete()
    return redirect('index')

blog/templates/blog/login.html
{% extends 'baseline.html' %}
{% block style %}
   body{
    background: url(http://mymaplist.com/img/parallax/back.png);
	background-color: #444;
    background: url(http://mymaplist.com/img/parallax/pinlayer2.png),url(http://mymaplist.com/img/parallax/pinlayer1.png),url(http://mymaplist.com/img/parallax/back.png);
    }

{% endblock %}

{% block body %}
  <div class="container">
    <div style="padding-top: 100px" class="row vertical-offset-100">
    	<div class="col-md-4 col-md-offset-3">
    		<div class="panel panel-default">
			  	<div class="panel-heading">
			    	<h3 class="panel-title">로그인하기</h3>
			 	</div>
			  	<div class="panel-body">
                    {# login form #}
			    	<form accept-charset="UTF-8" id="loginform" method="post">
                        {% csrf_token %}
                    <fieldset>
			    	  	<div class="form-group">
			    		    <input id="id_nickname" class="form-control" placeholder="Nickname" name="username" type="text">
			    		</div>
			    		<div class="form-group">
			    			<input id="id_password" class="form-control" placeholder="Password" name="password" type="password">
			    		</div>
			    		<div class="checkbox">
			    	    	<label>
			    	    		<input name="remember" type="checkbox" value="Remember Me"> Remember Me
			    	    	</label>
			    	    </div>
			    		<input class="btn btn-lg btn-success btn-block" type="submit" value="Login">
			    	</fieldset>
			      	</form>
			    </div>
			</div>
             {% if form.errors %}
                 <br>
                 <p>ID나 비밀번호가 일치하지 않습니다.</p>
             {% endif %}
		</div>
	</div>
</div>
{% endblock %}

blog/templates/blog/mypage.html
{% extends 'baseline.html' %}

{% block body %}
    <h3>프로필</h3>
    <hr>
    <div style="float: left">
        <img style="margin: 20px" height="200px" width="200px" src="{{ user.avatar.url }}">
        <form method="post" enctype="multipart/form-data" action="{% url 'blog:change_avatar' %}">
            {% csrf_token %}
            <div style="text-align: center">
                <input style="margin-left: 10%;" type="file" name="avatar">
                <br>
                <button type="submit" class="btn btn-primary" >프로필 변경하기</button>
            </div>
        </form>
    </div>
    <div>
        <br>
        <p><strong>닉네임</strong> {{ user.nickname }}</p>
        <p><strong>이름</strong> {{ user.username }}</p>
        <p><strong>이메일</strong> {{ user.email }}</p>
    </div>
    <a type="button" href="{% url 'blog:signout' %}" class="btn btn-primary">회원탈퇴하기</a>
{% endblock %}

blog/templates/blog/postdetail.html
{% extends 'baseline.html' %}
{% block body %}
    <div>
        <a href="{% url 'blog:list' %}" class="btn btn-default" type="button">글 리스트 보기</a>
    <div style="float: right;">
        {% if user == post.author %}
            <a href="{% url 'blog:post_update' pk=post.pk%}" class="btn btn-info" type="button">수정</a>
            <a href="{% url 'blog:post_delete' pk=post.pk%}" class="btn btn-danger" type="button">삭제</a>
        {% endif %}
    </div>
    </div>

    <div style="min-height: 300px">
        <br>
        <label for="inputtitle" class="col-sm-2 control-label">제목</label><p class="col-sm-10">{{ post.title }}</p>
        <label for="inputauthor" class="col-sm-2 control-label">작성자</label><p class="col-sm-10"><img style="margin: 5px;" height="40px" width="40px" src="{{ post.author.avatar.url }}">{{ post.author }}</p>
        <label for="inputcreated_title" class="col-sm-2 control-label">작성일자</label><p class="col-sm-10">{{ post.created_date }}</p>
        <label for="inputcontent" class="col-sm-2 control-label">내용</label>
        <div class="col-sm-10">
          <p>{{ post.content|linebreaks }}</p>
        </div>
    </div>
    <div>
    <strong>댓글</strong> {{ post.comments.count }}
    <hr>
    {% for comment in post.comments.all %}
        <div class="comment">
            <div>
                <img style="float: left; margin-left: 30px; margin-right:5px;" height="40px" width="40px" src="{{ comment.author.avatar.url }}">
                <strong>{{ comment.author }}&nbsp;&nbsp;{{ comment.created_date }}</strong>
                {% if user == comment.author %}
                <a href="{% url 'blog:comment_remove' pk=comment.pk%}"><i style="color: red" class="glyphicon glyphicon-remove"></i></a>
                {% endif %}
            <div class="col-sm-offset-1">
                <p >{{ comment.text|linebreaks }}</p>
                </div>
            </div>


        </div>
    {% empty %}
        <p>댓글이 없습니다.</p>
    {% endfor %}
    <hr>
    </div>
    <form method="post" id="commentform" action="{% url 'blog:new_comment' pk=post.pk %}">
    {% csrf_token %}
        <textarea class="form-control" rows="3" id="inputtext" name="text" placeholder="댓글을 입력하세요" required="true"></textarea>
        <br>
        <button style="float: right" type="submit" class="btn btn-primary" >댓글달기</button>
    </form>

{% endblock %}

blog/templates/blog/postlist.html
{% extends 'baseline.html' %}
{% block body %}
    <a style="float: right" href="{% url 'blog:write_post' %}" type="button" class="btn btn-primary">글 쓰기</a>
    <table class="table table-hover">
        <thead>
            <th>제목</th>
            <th>작성자</th>
            <th>작성일자</th>
            <th>댓글수</th>
        </thead>
        {% for post in post_list %}
            <tr>
                <td><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></td>
                <td>{{ post.author }}</td>
                <td>{{ post.created_date }}</td>
                <td>{{ post.comments.count }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

blog/templates/blog/signup.html
{% extends 'baseline.html' %}
{% block body %}
    <h3>회원가입하기</h3>
    <hr>
    <div class="col-sm-offset-1 col-sm-5">
        <form class="form-horizontal" id="signup" method="post">
        {% csrf_token %}
          {% for field in form %}
          <div class="form-group">
            <p>{{ field.label }} {{field}}</p>
          </div>
        {% endfor %}
          <div class="form-group">
              <button type="submit" class="btn btn-default">가입하기</button>
          </div>
        {% if form.errors %}
            <br>
            <p>{{ form.errors }}</p>
        {% endif %}
        </form>
    </div>
{% endblock %}

blog/templates/blog/updatepost.html
{% extends 'baseline.html' %}
{% block body %}
    <a href="{% url 'blog:list' %}" class="btn btn-default" type="button">글 리스트 보기</a>
    <form class="form-horizontal" id="updatepost" method="post">
    {% csrf_token %}
      <div class="form-group">
        <label for="inputtitle" class="col-sm-2 control-label">제목</label>
        <div class="col-sm-9">
          <input type="text" class="form-control" id="inputtitle" name="title" value="{{ post.title }}">
        </div>
      </div>
        <div class="form-group">
        <label for="inputtitle" class="col-sm-2 control-label">작성자</label>
        <div class="col-sm-9">
          <p>{{ post.author }}</p>
        </div>
      </div>
      <div class="form-group">
        <label for="inputcontent" class="col-sm-2 control-label">내용</label>
        <div class="col-sm-9">
            <textarea class="form-control" rows="10" id="inputcontent" name="content">{{ post.content }}</textarea>
        </div>
      </div>
        <div class="form-group">
        <label for="inputcreated_date" class="col-sm-2 control-label">작성날짜</label>
        <div class="col-sm-9">
          <p>{{ post.created_date }}</p>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-default">수정완료</button>
        </div>
      </div>
    </form>
{% endblock %}

blog/templates/blog/writepost.html
{% extends 'baseline.html' %}
{% block body %}
    <a href="{% url 'blog:list' %}" class="btn btn-default" type="button">글 리스트 보기</a>
    <form class="form-horizontal" id="writepost" method="post">
    {% csrf_token %}
        <br>
      <div class="form-group">
        <label for="inputtitle" class="col-sm-2 control-label">제목</label>
        <div class="col-sm-9">
          <input type="text" class="form-control" id="inputtitle" name="title" placeholder="제목" required="true">
        </div>
      </div>
        <div>
          <label for="inputauthor" class="col-sm-2 control-label">작성자</label>
          <p class="col-sm-10">{{ user.nickname }}</p>
        </div>
      <div class="form-group">
        <label for="inputcontent" class="col-sm-2 control-label">내용</label>
        <div class="col-sm-9">
            <textarea wrap="hard"  class="form-control" rows="10" id="inputcontent" name="content" placeholder="내용을 입력하세요" required="true"></textarea>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-10">
            <br>
          <button type="submit" class="btn btn-primary">작성완료</button>
        </div>
      </div>
    </form>
{% endblock %}