blog/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(
        r'^login/$',
        auth_views.login,
        name='login',
        kwargs={
            'template_name': 'blog/login.html'
        }
    ),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^list/$', views.post_list_view, name='list'),
    url(r'^write/$', views.write_post_view, name='write_post'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail_view, name='post_detail'),
    url(r'^post/(?P<pk>[0-9]+)/delete/$', views.post_delete_view, name='post_delete'),
    url(r'^post/(?P<pk>[0-9]+)/update/$', views.post_update_view, name='post_update'),
    url(r'^post/(?P<pk>[0-9]+)/newcomment/$', views.new_comment_view, name='new_comment'),
    url(r'^comment/(?P<pk>[0-9]+)/remove/$', views.comment_remove_view, name='comment_remove'),
    url(r'^mypage/$', views.mypage_view, name='mypage'),
    url(r'^mypage/changeavatar/$', views.change_avatar_view, name='change_avatar'),
    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^signout/$', views.signout_view, name='signout')

]

dustmq/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.shortcuts import render
from django.conf.urls.static import static
from django.conf import settings


def index(request):
    return render(request, 'index.html')


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^$', index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/baseline.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>SB COMMUNITY</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
          margin-bottom: 0;
          border-radius: 0;
        }

        /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
        .row.content {height: 450px}

        /* Set gray background color and 100% height */
        .sidenav {
          padding-top: 20px;
          min-height: 140%;
        }
        body {
            background: #f1f1f1;
        }


        /* Set black background color, white text and some padding */
        footer {
          background-color: #555;
          color: white;
          padding: 15px;
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
            text-align: center;
        }

        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
          .sidenav {
            height: auto;
            padding: 15px;
          }
          .row.content {height:auto;}
        }

        #content_box {
            padding: 20px;
            background: white;
            min-height: 140%;
        }
        #body_box{
            margin-bottom: 50px;
        }

      </style>
    </head>
    <body>

    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'index' %}">SB COMMUNITY</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'index' %}">Home</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
              {% if user.is_authenticated %}
                  <li><a href="{% url 'blog:mypage' %}"> Mypage</a></li>
                  <li><a href="{% url 'blog:logout' %}"> Logout</a></li>
              {% else %}
                  <li><a href="{% url 'blog:signup' %}"><span class="glyphicon glyphicon-pencil"></span> SignUp</a></li>
                 <li><a href="{% url 'blog:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
              {% endif %}
          </ul>
        </div>
      </div>
    </nav>


    <div id ="body_box" class="container-fluid text-center">
      <div class="row content">
        <div class="col-sm-2 sidenav" style="">
          {% if user.is_authenticated %}
            <p>어서오세요! {{ user.username }}님</p>
          {% endif%}
        </div>
        <div id="content_box" class="col-sm-8 text-left">
            {% block body %}{% endblock %}
        </div>
        <div class="col-sm-2 sidenav">
        </div>
      </div>
    </div>

    <footer class="container-fluid text-center">
      <p>수빙</p>
    </footer>

    </body>
    <script>
        {% block script %}{% endblock %}
    </script>
</html>

templates/index.html
{% extends 'baseline.html' %}
{% block body %}
    <h1>Welcome</h1>
    <p>커뮤니티 사이트 입니다. 환영합니다~ 많이 놀러오세요</p>
    <hr>
    <div class="text-center">
        <h3>Test</h3>
        <p>글을 작성하고 여러 의견을 나누어 보아요!</p>
        <a href="{% url 'blog:list' %}" type="button" class="btn btn-primary">글 보러가기</a>
    </div>
{% endblock %}